-- ⚠ 自動生成ファイル。手で編集しないでください。
-- 再生成: node supabase/generate_seed.mjs（data/cards.js が正）
-- カードマスタ（47枚）を public.cards に upsert します。

insert into public.cards
  (id, no, name, variant, rarity, art, image_url, obtain_condition, gacha, gacha_bucket, months, sort)
values
  ('akito-n01', '001', 'あきと', '実験ラボ', 'NORMAL', 'full', './assets/cards/akito-n01.png', '通常ガチャで入手', false, null, null, 0),
  ('akito-n02', '002', 'あきと', 'サッカー', 'NORMAL', 'full', './assets/cards/akito-n02.png', '通常ガチャで入手', false, null, null, 1),
  ('akito-n03', '003', 'あきと', '烈火バー', 'NORMAL', 'full', './assets/cards/akito-n03.png', '通常ガチャで入手', false, null, null, 2),
  ('akito-n04', '004', 'あきと', '野球', 'NORMAL', 'full', './assets/cards/akito-n04.png', '通常ガチャで入手', false, null, null, 3),
  ('akito-n05', '005', 'あきと', 'バレー', 'NORMAL', 'full', './assets/cards/akito-n05.png', '通常ガチャで入手', false, null, null, 4),
  ('akito-n06', '006', 'あきと', 'おだやか', 'NORMAL', 'full', './assets/cards/akito-n06.png', '通常ガチャで入手', false, null, null, 5),
  ('akito-n07', '007', 'あきと', 'バスケ', 'NORMAL', 'full', './assets/cards/akito-n07.png', '通常ガチャで入手', false, null, null, 6),
  ('akito-n08', '008', 'あきと', 'のんびり夏', 'NORMAL', 'full', './assets/cards/akito-n08.png', '通常ガチャで入手', false, null, null, 7),
  ('akito-n09', '009', 'あきと', '夜の支配者', 'NORMAL', 'full', './assets/cards/akito-n09.png', '通常ガチャで入手', false, null, null, 8),
  ('akito-r01', '010', 'あきと', '紅月の影忍', 'RARE', 'full', './assets/cards/akito-r01.png', '通常ガチャ（低確率）で入手', false, null, null, 9),
  ('akito-r02', '011', 'あきと', '鎖のハンター', 'RARE', 'full', './assets/cards/akito-r02.png', '通常ガチャ（低確率）で入手', false, null, null, 10),
  ('akito-sr01', '012', 'あきと', '忍・チャクラ', 'SR', 'full', './assets/cards/akito-sr01.png', 'イベント・特別ガチャで入手', false, null, null, 11),
  ('akito-sr02', '013', 'あきと', '夜のAKITO BAR', 'SR', 'full', './assets/cards/akito-sr02.png', 'イベント・特別ガチャで入手', false, null, null, 12),
  ('akito-ssr01', '014', 'あきと', '誕生日シャンパン', 'SSR', 'full', './assets/cards/akito-ssr01.png', '誕生日の来店記念で入手（9月・オリシャンを注文）', false, null, null, 13),
  ('kakeru-n01', '015', 'かける', '居酒屋サムズアップ', 'NORMAL', 'full', './assets/cards/kakeru-n01.png', '通常ガチャで入手', false, null, null, 14),
  ('kakeru-n02', '016', 'かける', 'うさぎふれあい', 'NORMAL', 'full', './assets/cards/kakeru-n02.png', '通常ガチャで入手', false, null, null, 15),
  ('kakeru-n03', '017', 'かける', 'バスケ', 'NORMAL', 'full', './assets/cards/kakeru-n03.png', '通常ガチャで入手', false, null, null, 16),
  ('kakeru-n04', '018', 'かける', 'バレー', 'NORMAL', 'full', './assets/cards/kakeru-n04.png', '通常ガチャで入手', false, null, null, 17),
  ('kakeru-n05', '019', 'かける', '旅の剣豪', 'NORMAL', 'full', './assets/cards/kakeru-n05.png', '通常ガチャで入手', false, null, null, 18),
  ('kakeru-n06', '020', 'かける', 'クールバー', 'NORMAL', 'full', './assets/cards/kakeru-n06.png', '通常ガチャで入手', false, null, null, 19),
  ('kakeru-n07', '021', 'かける', 'ダークフレイム', 'NORMAL', 'full', './assets/cards/kakeru-n07.png', '通常ガチャで入手', false, null, null, 20),
  ('kakeru-n08', '022', 'かける', '高校野球', 'NORMAL', 'full', './assets/cards/kakeru-n08.png', '通常ガチャで入手', false, null, null, 21),
  ('kakeru-n09', '023', 'かける', 'サッカー', 'NORMAL', 'full', './assets/cards/kakeru-n09.png', '通常ガチャで入手', false, null, null, 22),
  ('kakeru-r01', '024', 'かける', '稲妻ステップ', 'RARE', 'full', './assets/cards/kakeru-r01.png', '通常ガチャ（低確率）で入手', false, null, null, 23),
  ('kakeru-r02', '025', 'かける', 'クールドリブル', 'RARE', 'full', './assets/cards/kakeru-r02.png', '通常ガチャ（低確率）で入手', false, null, null, 24),
  ('kakeru-sr01', '026', 'かける', '海賊BAR', 'SR', 'full', './assets/cards/kakeru-sr01.png', 'イベント・特別ガチャで入手', false, null, null, 25),
  ('kakeru-sr02', '027', 'かける', 'いたずら忍者', 'SR', 'full', './assets/cards/kakeru-sr02.png', 'イベント・特別ガチャで入手', false, null, null, 26),
  ('kakeru-ssr01', '028', 'かける', '誕生日シャンパン', 'SSR', 'full', './assets/cards/kakeru-ssr01.png', '誕生日の来店記念で入手（7/8・オリシャンを注文）', false, null, null, 27),
  ('shoma-n01', '029', 'しょうま', 'かていモンスター', 'NORMAL', 'full', './assets/cards/shoma-n01.png', '通常ガチャで入手', false, null, null, 28),
  ('shoma-n02', '030', 'しょうま', 'バレー', 'NORMAL', 'full', './assets/cards/shoma-n02.png', '通常ガチャで入手', false, null, null, 29),
  ('shoma-n03', '031', 'しょうま', '肉塊バッター', 'NORMAL', 'full', './assets/cards/shoma-n03.png', '通常ガチャで入手', false, null, null, 30),
  ('shoma-n04', '032', 'しょうま', 'バスケ', 'NORMAL', 'full', './assets/cards/shoma-n04.png', '通常ガチャで入手', false, null, null, 31),
  ('shoma-n05', '033', 'しょうま', 'サッカー', 'NORMAL', 'full', './assets/cards/shoma-n05.png', '通常ガチャで入手', false, null, null, 32),
  ('shoma-n06', '034', 'しょうま', 'おどけムード', 'NORMAL', 'full', './assets/cards/shoma-n06.png', '通常ガチャで入手', false, null, null, 33),
  ('shoma-n07', '035', 'しょうま', '全力バレー', 'NORMAL', 'full', './assets/cards/shoma-n07.png', '通常ガチャで入手', false, null, null, 34),
  ('shoma-n08', '036', 'しょうま', 'しずかな圧', 'NORMAL', 'full', './assets/cards/shoma-n08.png', '通常ガチャで入手', false, null, null, 35),
  ('shoma-r01', '037', 'しょうま', 'ブレイブオーラ', 'RARE', 'full', './assets/cards/shoma-r01.png', '通常ガチャ（低確率）で入手', false, null, null, 36),
  ('shoma-r02', '038', 'しょうま', '天才メカニック', 'RARE', 'full', './assets/cards/shoma-r02.png', '通常ガチャ（低確率）で入手', false, null, null, 37),
  ('shoma-sr01', '039', 'しょうま', 'Good Vibes Only', 'SR', 'full', './assets/cards/shoma-sr01.png', 'イベント・特別ガチャで入手', false, null, null, 38),
  ('shoma-sr02', '040', 'しょうま', 'ナイトライフ', 'SR', 'full', './assets/cards/shoma-sr02.png', 'イベント・特別ガチャで入手', false, null, null, 39),
  ('shoma-sr03', '041', 'しょうま', 'カリスマオーラ', 'SR', 'full', './assets/cards/shoma-sr03.png', 'イベント・特別ガチャで入手', false, null, null, 40),
  ('shoma-ssr01', '042', 'しょうま', '誕生日シャンパン', 'SSR', 'full', './assets/cards/shoma-ssr01.png', '誕生日の来店記念で入手（3月・オリシャンを注文）', false, null, null, 41),
  ('yuta-ssr01', '043', 'ゆうた', '誕生日シャンパン', 'SSR', 'full', './assets/cards/yuta-ssr01.png', '誕生日の来店記念で入手（3/10・オリシャンを注文）', false, null, null, 42),
  ('akito-secret01', '044', 'あきと', '夏夜の影', 'SECRET', 'full', './assets/cards/akito-secret01.png', '夏限定ガチャ（7・8月）でSRと同確率で入手', true, 'SR', array[7,8]::int[], 43),
  ('kakeru-secret01', '045', 'かける', '夏夜のスピードスター', 'SECRET', 'full', './assets/cards/kakeru-secret01.png', '夏限定ガチャ（7・8月）でSRと同確率で入手', true, 'SR', array[7,8]::int[], 44),
  ('yuta-secret01', '046', 'ゆうた', '夏夜の支配者', 'SECRET', 'full', './assets/cards/yuta-secret01.png', '夏限定ガチャ（7・8月）でSRと同確率で入手', true, 'SR', array[7,8]::int[], 45),
  ('shoma-secret01', '047', 'しょうま', '夏夜のジェントルマン', 'SECRET', 'full', './assets/cards/shoma-secret01.png', '夏限定ガチャ（7・8月）でSRと同確率で入手', true, 'SR', array[7,8]::int[], 46)
on conflict (id) do update set
  no = excluded.no,
  name = excluded.name,
  variant = excluded.variant,
  rarity = excluded.rarity,
  art = excluded.art,
  image_url = excluded.image_url,
  obtain_condition = excluded.obtain_condition,
  gacha = excluded.gacha,
  gacha_bucket = excluded.gacha_bucket,
  months = excluded.months,
  sort = excluded.sort;
